#pragma once

enum {
    EXC_UNKNOWN=26710001,
    EXC_INIT_RTC_FAILED,
    EXC_CREATE_ALARM_TASK_FAILED,
    EXC_CREATE_SCANNER_TASK_FAILED,
    EXC_CREATE_UI_TASK_FAILED,
    EXC_INIT_OLED_FAILED,
    EXC_CREATE_DEVLST_UPDATER_TASK_FAILED,
};